# frozen_string_literal: true

require "yaml"
require "pathname"
require_relative "yml_format"

module Escriba
  # Dumps every translation to one YAML file per locale (escriba.<locale>.yml)
  # under the given directory — the standard config/locales layout — replacing
  # any previously dumped escriba.*.yml. Regeneration is lossless: values the
  # local database doesn't have are carried over from the previous dump (see
  # #read_existing). The files use the same escriba.<key> structure the
  # backend looks up, so shipping them in a PR makes the copies live right
  # after deploy: the backend falls back to them for keys the database doesn't
  # have yet.
  #
  # Every supported locale gets the full catalog of keys; untranslated strings
  # are dumped as blank skeleton entries, each annotated with the source copy
  # as a comment, so developers can fill them in. When the dev locale is
  # served from source code its file is skipped (that locale never reads the
  # DB or the files).
  class YmlDumper
    PLURAL_FORM_ORDER = KeyDeriver::PLURAL_FORM_KEYS.map(&:to_s).freeze
    HEADER = <<~HEADER
      # Generated by `bin/rails escriba:dump_yml` — do not edit the keys.
      # Blank entries are untranslated: fill them in and they are served after
      # the next deploy, until the database has a value for them (an edit in
      # the admin UI always takes precedence).
    HEADER

    # extracted: SourceExtractor::ExtractedString entries; they complete the
    # catalog with strings the database hasn't discovered yet (the DB only
    # learns about a string the first time it executes).
    def initialize(dir:, extracted: [])
      @dir = Pathname.new(dir)
      @extracted = extracted
    end

    # Returns the written file paths.
    def dump!
      @dir.mkpath
      existing = read_existing
      Dir[@dir.join(YmlFormat::FILE_GLOB).to_s].each { |stale| File.delete(stale) }

      locales.map { |locale| write_locale(locale, existing[locale.to_s] || {}) }
    end

    private

    def locales
      all = Escriba.config.available_locales.map(&:to_sym)
      Escriba.config.dev_locale_from_code ? all - [Escriba.config.dev_locale] : all
    end

    # The known strings: dev-locale rows, completed with statically extracted
    # ones the database hasn't seen yet. Both respond to the same reader
    # interface (key/source_copy/meaning/plural).
    def catalog
      @catalog ||= begin
        rows = Escriba::Translation.for_locale(Escriba.config.dev_locale).to_a
        known = rows.to_h { |row| [row.key, true] }
        (rows + @extracted.reject { |entry| known[entry.key] }).sort_by { |entry| source_text(entry) }
      end
    end

    # The previous dump's values, per locale. They complete the database: a
    # developer's local DB usually lacks translations that teammates committed
    # straight to these files, and regenerating must not blank those out.
    def read_existing
      Dir[@dir.join(YmlFormat::FILE_GLOB).to_s].to_h do |file|
        [YmlFormat.locale_of(file), YmlFormat.entries(file)]
      end
    end

    def write_locale(locale, existing)
      values = Escriba::Translation.for_locale(locale).index_by(&:key)
      path = @dir.join(YmlFormat.file_name(locale))
      File.write(path, file_content(locale, values, existing))
      path
    end

    def file_content(locale, values, existing)
      lines = [HEADER.chomp, "#{locale}:"]
      if catalog.empty?
        lines << "  #{YmlFormat::NAMESPACE}: {}"
      else
        lines << "  #{YmlFormat::NAMESPACE}:"
        catalog.each { |dev| lines.concat(entry_lines(dev, values[dev.key], existing[dev.key])) }
      end
      lines.join("\n") + "\n"
    end

    def entry_lines(dev, row, existing_value)
      indent = " " * 4
      comment_lines(dev, indent) + value_lines(dev, row, existing_value, indent)
    end

    def comment_lines(dev, indent)
      lines = source_text(dev).split("\n").map { |line| "#{indent}# #{line}" }
      lines << "#{indent}# meaning: #{dev.meaning}" if dev.meaning.present?
      lines
    end

    # Value precedence: database, then the previous dump, then a blank
    # skeleton — mirroring the runtime lookup order (DB first, files second).
    def value_lines(dev, row, existing_value, indent)
      value = row&.value
      value = existing_value if blank_value?(value)
      value = skeleton(dev) if blank_value?(value)
      value = ordered_forms(value) if value.is_a?(Hash)

      # Serializing each entry through Psych keeps quoting/escaping correct;
      # re-indenting every line by the same amount preserves validity.
      YAML.dump({ dev.key => value }).sub(/\A---\n/, "").chomp.split("\n").map { |line| "#{indent}#{line}" }
    end

    def skeleton(dev)
      if dev.plural && dev.source_copy.is_a?(Hash)
        dev.source_copy.keys.to_h { |form| [form.to_s, ""] }
      else
        ""
      end
    end

    def blank_value?(value)
      if value.is_a?(Hash)
        value.values.all? { |v| v.to_s.strip.empty? }
      else
        value.to_s.strip.empty?
      end
    end

    def ordered_forms(forms)
      forms
        .transform_keys(&:to_s)
        .sort_by { |form, _| PLURAL_FORM_ORDER.index(form) || PLURAL_FORM_ORDER.size }
        .to_h
    end

    def source_text(dev)
      Escriba.source_text(dev)
    end
  end
end
