source "https://rubygems.org"

gem "rails"

gem "sqlite3", ">= 2.1"
gem "puma"

gem "turbo-rails"
gem "stimulus-rails"
gem "importmap-rails"
gem "propshaft"

gem "escriba", path: "../gem"

group :development do
  gem "listen"
end

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
