# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in escriba.gemspec
gemspec

gem "rake", "~> 13.0"

gem "minitest", "~> 5.16"
gem "simplecov", require: false
gem "simplecov_json_formatter", require: false
